hashtag: bhtom_UZPW50_Chile_QHY268PRO_michal_zejmo_52188231a24f129f67363b9e1b176e05
bhtom_url: https://bh-tom.astrolabs.pl/photometry-upload/

radius: 2.0

object_key: OBJECT
filter_key: FILTER
filter_map: 
  B: APASS/B
  V: APASS/V
  R: APASS/r

# if no filter map needed leave it empty
# filter_map: 